### ISSUE TITLE
Missing imfile.txt

### ISSUE THREAD

**Issue by shubhambodhe** [keshusharmamrt/FOTS-Scene-Text-Parsing#1]
In your FOTS_Scene_Text_Parsing.ipynb notebook you have a cell that is moving imlist.txt file and Words2.zip from drive to colab's local workspace.

shutil.move('./drive/My Drive/imlist.txt','.')

!unzip './drive/My Drive/Words2.zip' -d '.'

I was wondering where did you get this file from as I couldn't find it in the github repo

**Comment by keshusharmamrt** [comment]
Hi, This imlist file and Word2.zip I saved in my local drive and then used them in my colab's workspace.
imlist file contains the list of all files images  that were generated in text_image_generation() function and Words2.zip contians those images.
